name: Update GitHub Stats

on:
  schedule:
    # 03:00 no horário de Brasília (UTC-3)
    - cron: "0 6 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Atualizar cache dos cards
        run: |
          TIMESTAMP=$(date +%s)

          sed -i "s/&v=[0-9]*/\&v=$TIMESTAMP/g" README.md

      - name: Salvar atualização
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "Nenhuma alteração necessária."
          else
            git add README.md
            git commit -m "chore: atualizar GitHub stats"
            git push
          fi
